package com.gaspar.modwvwbot.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;

import java.nio.file.Path;

/**
 * Result of a {@link com.gaspar.modwvwbot.misc.LogProcessorTask}.
 */
@Data
@AllArgsConstructor
@Builder
public class LogProcessingResult {

    /**
     * This will only be true, if the processing was successful.
     * Don't try to use the result if this is false.
     */
    private boolean success;

    /**
     * Name of the log file that the user uploaded to discord.
     */
    private String originalFileName;

    /**
     * Dps.report permalink of this file.
     */
    private String permalink;

    /**
     * Path to JSON file that was generated by dps.report and then cleaned.
     */
    private Path pathToCleanedJson;

    /**
     * File name of cleaned JSON.
     */
    private String nameOfCleanedJson;

    /**
     * Original JSON size in bytes.
     */
    private long originalSize;

    /**
     * Cleaned JSON size in bytes.
     */
    private long cleanedSize;

}
