## active in all profiles -------------------------------------------
server:
  port: ${MWB_PORT:8080}
com:
  gaspar:
    modwvwbot:
      security_token: ${SECURITY_TOKEN}
      discord_token: ${BOT_DISCORD_TOKEN}
      default_reminder_minutes: 15
      gw2_api_url: https://api.guildwars2.com
      gw2_api_key_url: https://account.arena.net/applications
      gw2_api_key_length: 72
      gw2_api_key_regex: ^[-A-Z0-9]+$
      gw2_api_key_permissions: account, inventories, characters, wallet, unlocks, progression
      emote_ids:
        gem: 970640961468248144
        commander: 970638912458469426
        loading: 971306366687928371
      nubaras_discord_id: 416289572289249280
      documentation_url: https://gtomika.github.io/mod-wvw-bot/

spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
---
## active in debug profile -------------------------------------------
spring:
  config:
    activate:
      on-profile:
        - debug
  datasource:
    # these are just for local dev environment
    url: jdbc:postgresql://localhost:5432/modwvwbot
    username: modwvwbot
    password: modwvwbot
logging:
  config: classpath:log4j2-debug.xml
  level:
    com:
      gaspar:
        modwvwbot: debug # project classes LOG debug level
    root: info # non-project classes log INFO level
---
## active in release profile -------------------------------------------
spring:
  config:
    activate:
      on-profile:
        - release
  datasource:
    url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT}/${RDS_DB_NAME}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
logging:
  config: classpath:log4j2-release.xml
  level:
    root: INFO